PROGRAM:    
    STATEMENTS END
    ;

STATEMENTS:  
    STATEMENT
    | STATEMENTS STATEMENT 
    | END 
    ;

STATEMENT: 
    DECLARATION
    | ATTRIBUTION
    | IF_STMT
    | READ_EXP
    | PRINT_EXP
    | BLOCK
    | EOL
    ;

IF_STMT: 
    IF P_LEFT EXP P_RIGHT BLOCK EOL
    | IF P_LEFT EXP P_RIGHT BLOCK ELSE BLOCK EOL
    ;

BLOCK: 
    BRACES_LEFT STATEMENTS BRACES_RIGHT
    ;

ATTRIBUTION: 
    IDENTIFIER EQUALS EXP EOL
    | IDENTIFIER EQUALS SQRT_EXP EOL
    ;

EXP:
    NUMBER
    | IDENTIFIER
    | EXP OPERATOR EXP
    | P_LEFT EXP P_RIGHT
    | NOT EXP
    ;

SQRT_EXP: 
    SQRT P_LEFT IDENTIFIER P_RIGHT
    ;

PRINT_EXP:
    PRINT P_LEFT IDENTIFIER P_RIGHT EOL
    | PRINT P_LEFT STRING P_RIGHT EOL
    ;

READ_EXP:
    READ P_LEFT IDENTIFIER P_RIGHT EOL
    ;

DECLARATION:
    TYPE IDENTIFIER EOL
    ;